config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :crews
  resources :ratings
  resources :tags
  resources :genres
  resources :movies
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  #, :skip => [:registrations]

  devise_scope :user do
    get 'edit_user_registration', to: 'users#edit'
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'movies#index'

  get '/schema' => 'pages#sch'
  get '/mid-semester' => 'pages#mid'
  get '/final' => 'pages#final'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.is?("Manager")
      can :manage, Movie
      can :manage, Crew
    elsif user.is?("Admin")
      can :manage, :all
      can :manage, User
    elsif user.is?("Registered")
      can :manage, Rating
    end
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/crew.rb
class Crew < ApplicationRecord
	has_many :crew_roles
	has_many :movie_crews

	has_many :roles, through: :crew_roles, dependent: :destroy
	has_many :movies, through: :movie_crews, dependent: :destroy
end

app/models/crew_role.rb
class CrewRole < ApplicationRecord
  belongs_to :crew
  belongs_to :role
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :movie_genres
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_genres
	has_many :movie_tags
	has_many :movie_ratings
	has_many :movie_crews
	has_many :watchlists
	
	has_many :genres, through: :movie_genres, dependent: :destroy
	has_many :tags, through: :movie_tags, dependent: :destroy
	has_many :ratings, through: :movie_ratings, dependent: :destroy
	has_many :crews, through: :movie_crews, dependent: :destroy
	has_many :users, through: :watchlists, dependent: :destroy



end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :movie
  belongs_to :crew
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie_rating.rb
class MovieRating < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  belongs_to :rating
end

app/models/movie_tag.rb
class MovieTag < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
	has_many :movie_ratings
	has_many :movies, through: :movie_ratings, dependent: :destroy
	has_many :users, through: :movie_ratings, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :crew_roles

	has_many :crews, through: :crew_roles, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :movie_tags
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :watchlists
  has_many :movie_ratings

  has_many :movies, through: :watchlists, dependent: :destroy
  has_many :ratings, through: :movie_ratings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  serialize :permissions, Hash
  serialize :watchlist, Array

  PERMISSIONS = [
  	"Registered",
    "Manager",
  	"Admin"
  ]

  def is?(param)
	  if PERMISSIONS.include?(param) # continue
	    permissions[param] ? true : false
	  else # this is bad, raise
	    raise "User cannot be #{param}"
	  end
	end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # def mgenres
  #   @genre = Genre.all
  # end


  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
       # @movies = Movie.all.paginate(page: params[:page], per_page: 10).preload(:review)
  end


  # GET /movies/1
  # GET /movies/1.json
  def show
    @genre = Genre.all
    @tag = Tag.all
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @genre = Genre.all
    @tag = Tag.all
  end

  # GET /movies/1/edit
  def edit
    @genre = Genre.all
    @tag = Tag.all
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(
        :title, 
        :summary, 
        :release, 
        :language, 
        :duration, 
        :image, 
        :video, 
        {genre_ids: []}, 
        {tag_ids: []},
        {crew_ids: []},
        :watchlists
        )
    end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :summary %>
    <%= f.text_area :summary %>
  </div>

  <div class="field">
    <%= f.label :release %>
    <%= f.number_field :release %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.number_field :duration %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.text_field :video %>
  </div>

  <div class="field">
    <%= f.label :genre_ids %>
    <%= f.select :genre_ids, Genre.all.map{ |g| [g.name, g.id] }, {}, { multiple: :multiple, include_hidden: false } %>
  </div>

  <div class="field">
    <%= f.label :tag_ids %>
    <%= f.select :tag_ids, Tag.all.map{ |t| [t.name, t.id] }, {}, { multiple: :multiple, include_hidden: false } %>
  </div>

  <div class="field">
    <%= f.label :crew_ids %>
    <%= f.select :crew_ids, Crew.all.map{ |c| [c.name, c.id] }, {}, { multiple: :multiple, include_hidden: false } %>
    <%# f.select :crew.crew_roles.role_ids, Roles.all.map{ |r| [r.name, r.id]}, {}, { multiple: :multiple, include_hidden: false } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_table.html.erb
<table class="standard" >
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Release</th>
      <th>Language</th>
      <th>Duration</th>
      <th>Genres</th>
      <th>Tags</th>
      <th>Ratings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr class="<%= cycle('odd','even') %>" >
        <td><%= movie.title %></td>
        <td><%= movie.summary %></td>
        <td><%= movie.release %></td>
        <td><%= movie.language %></td>
        <td><%= movie.duration %></td>
        <td><%= movie.genres.collect(&:name).join(" & ") %></td>
        <td><%= movie.tags.collect(&:name).join(" & ") %></td>
        <td>
          <% if movie.ratings.size() == 0 %>
          Not Rated
          <% else %>
            <% total = movie.ratings.collect(&:rating).inject(0){|sum,x| (sum + x) } %>
            <%= (total/movie.ratings.size()) %>
          <% end %>
        </td>
        <td><%= link_to 'Show', movie %></td>
<% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
  <% if current_user.is?("Admin") %>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/edit.html.erb
<h1 class="page-title" >Editing Movie</h1>

<div class="indent">

	<% if current_user.is?("Manager") %>
		<%= render 'form', movie: @movie %>
	<% else %>

		<%= form_for(@movie) do |f| %>
		  <% if @movie.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

		      <ul>
		      <% @movie.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

			<div class="field">
		    <%= f.label :tag_ids %>
		    <%= f.select :tag_ids, Tag.all.map{ |t| [t.name, t.id] }, {}, { multiple: :multiple, include_hidden: false } %>
		  </div>
		   <div class="actions">
		    <%= f.submit %>
		  </div>
		<% end %>
	<% end %>

	<div class="field">
		Or Make your Own Tag!
	</div>
	<%= button_to 'Make a Tag', new_tag_path, method: :get %>
	<br>
	<br>

	<%= link_to 'Show', @movie %> |
	<%= link_to 'Back', movies_path %>
</div>

app/views/movies/index.html.erb
<h1 class="page-title" >Movies</h1>



<%= render('table', movies: @movies, paginate: true) %>

<!-- <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Release</th>
      <th>Language</th>
      <th>Duration</th>
      <th>Image</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @movies.each do |movie| %>
      <tr>
        <td><%# movie.title %></td>
        <td><%# movie.summary %></td>
        <td><%# movie.release %></td>
        <td><%# movie.language %></td>
        <td><%# movie.duration %></td>
        <td><%# movie.image %></td>
        <td><%# movie.video %></td>
        <td><%# link_to 'Show', movie %></td>
        <td><%# link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%# link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table> -->

<br>


<% if user_signed_in? %>
  <% if current_user.is?("Manager") %>
    <div class="indent">
      <%= link_to 'New Movie', new_movie_path %>
    </div>
  <% end %>
<% end %>

app/views/movies/new.html.erb
<h1 class="page-title" >New Movie</h1>

<div class="indent">
	<%= render 'form', movie: @movie %>

	<%= link_to 'Back', movies_path %>
</div>

app/views/movies/show.html.erb
<h1 class="page-title" ><%= @movie.title %></h1>

<div class="indent">

  <div class="col-2">

    <div class="col-div left div" >

    <center>

      <img src="<%= @movie.image %>" style="height: 40vh; width: 50vh;" >

      <% phrase = @movie.video[32..-1] %>

      <iframe 
        width="500vw" 
        height="400vh" 
        src="https://www.youtube.com/embed/<%= phrase %>" 
        frameborder="0" 
        allowfullscreen>  
      </iframe>

    </center>

    </div>

    <div class="col-div right-div">

      <div class="indent">

        

        <p class="details" >
          <strong>Genre(s):</strong><br><br>
          <%= @movie.genres.collect(&:name).join(" & ") %>
        </p>

        <%# This is where the RATING will go %>

        <p class="details" >
          <strong>Summary:</strong><br><br>
          <%= @movie.summary %>
        </p>

        <p class="details" >
          <strong>Release:</strong><br><br>
          <%= @movie.release %>
        </p>

        <p class="details" >
          <strong>Language:</strong><br><br>
          <%= @movie.language %>
        </p>

        <p class="details" >
          <strong>Duration:</strong><br><br>
          <%= @movie.duration %>
        </p>

        <p class="details" >
          <strong>Tags:</strong><br><br>
          <%= @movie.tags.collect(&:name).join(" & ") %>
        </p>

        <p class="details">
          <strong>Rating:</strong><br><br>
          <% if @movie.ratings.size() == 0 %>
          Not Rated
          <% else %>
            <% total = @movie.ratings.collect(&:rating).inject(0){|sum,x| (sum + x) } %>
            <%= (total/@movie.ratings.size()) %>
          <% end %>
        </p>

        <p class="details" >
          <strong>Crew Members:</strong><br><br>
          <%= @movie.crews.collect(&:name).join(" & ") %>
        </p>

      </div>

    </div>

  </div>

<table class="standard" >
  <thead>
    <tr>
      <th>Review</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie.ratings.each do |rating| %>
      <tr class="<%= cycle('odd','even') %>" >
        <td><%= rating.review %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <br>
  <br>

<div class="indent">
  <% if user_signed_in? %>
    <% if current_user.is?("Manager") %>
      <%= link_to 'Edit', edit_movie_path(@movie) %> |
    <% end %>
  <% end %>
  <%= link_to 'Back', movies_path %>
</div>