config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :crews
  resources :ratings
  resources :tags
  resources :genres
  resources :movies
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  #, :skip => [:registrations]

  devise_scope :user do
    get 'edit_user_registration', to: 'users#edit'
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'movies#index'

  get '/schema' => 'pages#sch'
  get '/mid-semester' => 'pages#mid'
  get '/final' => 'pages#final'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.is?("Manager")
      can :manage, Movie
      can :manage, Crew
    elsif user.is?("Admin")
      can :manage, :all
      can :manage, User
    elsif user.is?("Registered")
      can :manage, Rating
    end
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crew.rb
class Crew < ApplicationRecord
	has_many :crew_roles
	has_many :movie_crews

	has_many :roles, through: :crew_roles, dependent: :destroy
	has_many :movies, through: :movie_crews, dependent: :destroy
end

app/models/crew_role.rb
class CrewRole < ApplicationRecord
  belongs_to :crew
  belongs_to :role
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :movie_genres
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_genres
	has_many :movie_tags
	has_many :movie_ratings
	has_many :movie_crews
	has_many :watchlists
	
	has_many :genres, through: :movie_genres, dependent: :destroy
	has_many :tags, through: :movie_tags, dependent: :destroy
	has_many :ratings, through: :movie_ratings, dependent: :destroy
	has_many :crews, through: :movie_crews, dependent: :destroy
	has_many :users, through: :watchlists, dependent: :destroy



end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :movie
  belongs_to :crew
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie_rating.rb
class MovieRating < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  belongs_to :rating
end

app/models/movie_tag.rb
class MovieTag < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
	has_many :movie_ratings
	has_many :movies, through: :movie_ratings, dependent: :destroy
	has_many :users, through: :movie_ratings, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :crew_roles

	has_many :crews, through: :crew_roles, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :movie_tags
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :watchlists
  has_many :movie_ratings

  has_many :movies, through: :watchlists, dependent: :destroy
  has_many :ratings, through: :movie_ratings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  serialize :permissions, Hash
  serialize :watchlist, Array

  PERMISSIONS = [
  	"Registered",
    "Manager",
  	"Admin"
  ]

  def is?(param)
	  if PERMISSIONS.include?(param) # continue
	    permissions[param] ? true : false
	  else # this is bad, raise
	    raise "User cannot be #{param}"
	  end
	end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    @rating.users << User.find(current_user)
    # @rating.movies << Movie.find_by(@rating.movies)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:rating, :review, {movie_ids: []})
    end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_ids %>
    <%= f.select :movie_ids, Movie.all.map{ |m| [m.title, m.id] }, {}, { multiple: :multiple, include_hidden: false } %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_area :review %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/_table.html.erb
<table class="standard" >
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr class="<%= cycle('odd','even') %>" >
        <td><%= rating.users.collect(&:fname).join("") %></td>
        <td><%= rating.movies.collect(&:title).join("") %></td>
        <td><%= rating.rating %></td>
        <td><%= rating.review %></td>
        <td><%= link_to 'Show', rating %></td>
<% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1 class="page-title" >Ratings</h1>

<%= render('table', ratings: @ratings, paginate: true) %>


<!-- <table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @ratings.each do |rating| %>
      <tr>
        <td><%# rating.rating %></td>
        <td><%# rating.review %></td>
        <td><%# link_to 'Show', rating %></td>
        <td><%# link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%# link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table> -->

<br>

<% if user_signed_in? %>
  <div class="indent">
    <%= link_to 'New Rating', new_rating_path %>
  </div>
<% end %>

app/views/ratings/new.html.erb
<h1 class="page-title" >New Rating</h1>

<div class="indent">
	<%= render 'form', rating: @rating %>

	<%= link_to 'Back', ratings_path %>
</div>

app/views/ratings/show.html.erb
<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<p>
  <strong>Review:</strong>
  <%= @rating.review %>
</p>

<div class="indent">
	<%= link_to 'Edit', edit_rating_path(@rating) %> |
	<%= link_to 'Back', ratings_path %>
</div>	