config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :crews
  resources :ratings
  resources :tags
  resources :genres
  resources :movies
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  #, :skip => [:registrations]

  devise_scope :user do
    get 'edit_user_registration', to: 'users#edit'
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'movies#index'

  get '/schema' => 'pages#sch'
  get '/mid-semester' => 'pages#mid'
  get '/final' => 'pages#final'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.is?("Manager")
      can :manage, Movie
      can :manage, Crew
    elsif user.is?("Admin")
      can :manage, :all
      can :manage, User
    elsif user.is?("Registered")
      can :manage, Rating
    end
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crew.rb
class Crew < ApplicationRecord
	has_many :crew_roles
	has_many :movie_crews

	has_many :roles, through: :crew_roles, dependent: :destroy
	has_many :movies, through: :movie_crews, dependent: :destroy
end

app/models/crew_role.rb
class CrewRole < ApplicationRecord
  belongs_to :crew
  belongs_to :role
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :movie_genres
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_genres
	has_many :movie_tags
	has_many :movie_ratings
	has_many :movie_crews
	has_many :watchlists
	
	has_many :genres, through: :movie_genres, dependent: :destroy
	has_many :tags, through: :movie_tags, dependent: :destroy
	has_many :ratings, through: :movie_ratings, dependent: :destroy
	has_many :crews, through: :movie_crews, dependent: :destroy
	has_many :users, through: :watchlists, dependent: :destroy



end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :movie
  belongs_to :crew
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie_rating.rb
class MovieRating < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  belongs_to :rating
end

app/models/movie_tag.rb
class MovieTag < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
	has_many :movie_ratings
	has_many :movies, through: :movie_ratings, dependent: :destroy
	has_many :users, through: :movie_ratings, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :crew_roles

	has_many :crews, through: :crew_roles, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :movie_tags
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :watchlists
  has_many :movie_ratings

  has_many :movies, through: :watchlists, dependent: :destroy
  has_many :ratings, through: :movie_ratings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  serialize :permissions, Hash
  serialize :watchlist, Array

  PERMISSIONS = [
  	"Registered",
    "Manager",
  	"Admin"
  ]

  def is?(param)
	  if PERMISSIONS.include?(param) # continue
	    permissions[param] ? true : false
	  else # this is bad, raise
	    raise "User cannot be #{param}"
	  end
	end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_table.html.erb
<table class="standard" >
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr class="<%= cycle('odd','even') %>" >
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
<% if user_signed_in? %>
  <% if current_user.is?("Manager") %>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/edit.html.erb
<h1 class="page-title" >Editing Tag</h1>

<div class="indent">

	<%= render 'form', tag: @tag %>

	<%= link_to 'Show', @tag %> |
	<%= link_to 'Back', tags_path %>
</div>

app/views/tags/index.html.erb
<h1 class="page-title" >Tags</h1>

<%= render('table', tags: @tags, paginate: true) %>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @tags.each do |tag| %>
      <tr>
        <td><%# tag.name %></td>
        <td><%# link_to 'Show', tag %></td>
        <td><%# link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%# link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table> -->

<br>

<div class="indent">
  <%= link_to 'New Tag', new_tag_path %>
</div>

app/views/tags/new.html.erb
<h1 class="page-title" >New Tag</h1>


<div class="indent">
	<%= render 'form', tag: @tag %>

	<%= link_to 'Back', tags_path %>
</div>

app/views/tags/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<div class="indent">
	<% if user_signed_in? %>
  	<% if current_user.is?("Manager") %>
			<%= link_to 'Edit', edit_tag_path(@tag) %> |
		<% end %>
	<% end %>
	<%= link_to 'Back', tags_path %>
</div>