config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :crews
  resources :ratings
  resources :tags
  resources :genres
  resources :movies
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  #, :skip => [:registrations]

  devise_scope :user do
    get 'edit_user_registration', to: 'users#edit'
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'movies#index'

  get '/schema' => 'pages#sch'
  get '/mid-semester' => 'pages#mid'
  get '/final' => 'pages#final'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.is?("Manager")
      can :manage, Movie
      can :manage, Crew
    elsif user.is?("Admin")
      can :manage, :all
      can :manage, User
    elsif user.is?("Registered")
      can :manage, Rating
    end
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/crew.rb
class Crew < ApplicationRecord
	has_many :crew_roles
	has_many :movie_crews

	has_many :roles, through: :crew_roles, dependent: :destroy
	has_many :movies, through: :movie_crews, dependent: :destroy
end

app/models/crew_role.rb
class CrewRole < ApplicationRecord
  belongs_to :crew
  belongs_to :role
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :movie_genres
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_genres
	has_many :movie_tags
	has_many :movie_ratings
	has_many :movie_crews
	has_many :watchlists
	
	has_many :genres, through: :movie_genres, dependent: :destroy
	has_many :tags, through: :movie_tags, dependent: :destroy
	has_many :ratings, through: :movie_ratings, dependent: :destroy
	has_many :crews, through: :movie_crews, dependent: :destroy
	has_many :users, through: :watchlists, dependent: :destroy



end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :movie
  belongs_to :crew
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie_rating.rb
class MovieRating < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  belongs_to :rating
end

app/models/movie_tag.rb
class MovieTag < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
	has_many :movie_ratings
	has_many :movies, through: :movie_ratings, dependent: :destroy
	has_many :users, through: :movie_ratings, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :crew_roles

	has_many :crews, through: :crew_roles, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :movie_tags
	has_many :movies, through: :movie_genres, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :watchlists
  has_many :movie_ratings

  has_many :movies, through: :watchlists, dependent: :destroy
  has_many :ratings, through: :movie_ratings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  serialize :permissions, Hash
  serialize :watchlist, Array

  PERMISSIONS = [
  	"Registered",
    "Manager",
  	"Admin"
  ]

  def is?(param)
	  if PERMISSIONS.include?(param) # continue
	    permissions[param] ? true : false
	  else # this is bad, raise
	    raise "User cannot be #{param}"
	  end
	end

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title if @title %> | MoviBase</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<input type='checkbox' id='hamburger'>
<div id="header-bar">
  <label for='hamburger'> <%= image_tag 'menu-icon.png', id: 'hamburger-img' %>  </label>
  <table id="header-center">
  <tbody>
    <tr>
      <center>
        <h1 class="site-title" >MoviBase</h1>
      </center>
      </tr>
   </tbody>
   </table>
</div>

<nav class="menu" role="navigation">
  <% if user_signed_in? %>
    <p style="color: #fff;" >Logged in as

    <br/>

    <strong><%= current_user.fname %></strong>.</p>

    <div class="indent">
      <div class="col-2">
        <div class="col-div left div" >
          <%= button_to "Edit Account", edit_user_registration_path, method: :get %>
        </div>
        <div class="col-div right-div">
            <%= button_to "Logout", destroy_user_session_path, method: :delete %>
        </div>
      </div>
    </div>

      <center>
        <h1 class="page-title">Admin</h1>
      </center>

    <div class="indent">
      <ul>
        <% if current_user.is?("Admin") %>
        <li><%= link_to "Users", users_path %></li>
        <% end %>
        <li><%= link_to "Roles", roles_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
        <li><%= link_to "Genres", genres_path %></li>
      </ul>
    </div>

  <% end %>

			<center>
			  <h1 class="page-title">MENU</h1>
			</center>

  <%if ! user_signed_in?%>

	  <div class="indent">
	    <div class="col-2">
	      <div class="col-div left div" >

	        <%= button_to "Sign Up", new_user_registration_path, method: :get %>

	      </div>
	      <div class="col-div right-div">
	          <%= button_to "Login", new_user_session_path %>

	      </div>
	    </div>
	  </div>

  <%end%>

	  <ul>
	    <li><%= link_to "Home", root_path %></li>
	    <li><%= link_to "Movies", movies_path %></li>
	    <li><%= link_to "Reviews", ratings_path %></li>
	    <li><%= link_to "Crews", crews_path %></li>
	  </ul>

    <br>
    <br>
    <br>

</nav>

<div id="main-block">

	<br/>
  <p id="notice"><%= notice %></p>


	<%= yield %>

</div>

</body>
</html>

app/views/pages/final.html.erb
<h2 class="page-title">Final Deliverables</h2>

<div class="indent">
	<b><u>Here are the Final Deliverables due on April 21st:</u></b>
	<br>
	<br>
	<b>NOTE: We have to demo/present our Web Interface between April 17th to April 21st</b>
	<br>
	<br>
	<em><b>NOTE:</b></em> Items with a &#10004; have been completed. 
	<br>
	<br>
	For each team, please submit a compressed file containing the following: 
	<br>
	<ol>
		<li>A PDF report named “final-report.pdf” including:</li>
		<br>
		<ol>
			<li>Finalized database design and assumptions, ER diagram, and database schemawith sound design principle applied (the minimal requirements need to be met).</li><br>
			<li>The functionalities supported by your web application and screenshots illustrating the corresponding functionalities (the minimal requirements need to be met). </li><br>
			<li>Testing. Explain how you tested the functionalities of your application (e.g., how each functionality is tested, how the correctness of the query results is tested, etc.). </li><br>
			<li>Team member contribution. Clearly describe the contributions of each team member to the project. </li><br>
			<li>Experience and Challenges. Describe your experience and challenges you had during the project design and development process. </li><br>
		</ol>
		<li>A MySQL dump file named “movie-db.sql”, containing:</li><br>
		<ol>
			<li>CREATE TABLE statements (DDL) for each table. </li><br>
			<li>INSERT statements (DML) with at least 30 sample rows inserted for each table.I will use this in MySQL to create all your tables and load sample rows to perform my tests for grading.</li><br>
		</ol>
		<li>A folder named “web-app” containing all source code to make your web application run. The web application needs to properly work with the above MySQL databasedump “movie-sb.sql”. Source code should include proper documentation. A README file is at least required to specify how to run your application.</li>
	</ol>
	<br>
	<b><u>Our Final Deliverables So Far:</u></b>
	<br>
	<br>

	<ol>
		<li>A PDF report named “final-report.pdf” including:</li>
		<br>
		<ol>
			<li>Finalized database design and assumptions, ER diagram, and database schemawith sound design principle applied (the minimal requirements need to be met).</li><br>
			<li>The functionalities supported by your web application and screenshots illustrating the corresponding functionalities (the minimal requirements need to be met). </li><br>
			<li>Testing. Explain how you tested the functionalities of your application (e.g., how each functionality is tested, how the correctness of the query results is tested, etc.). </li><br>
			<li>Team member contribution. Clearly describe the contributions of each team member to the project. </li><br>
			<li>Experience and Challenges. Describe your experience and challenges you had during the project design and development process. </li><br>
		</ol>
		<li>A MySQL dump file named “movie-db.sql”, containing:</li><br>
		<ol>
			<li>CREATE TABLE statements (DDL) for each table. </li><br>
			<li>INSERT statements (DML) with at least 30 sample rows inserted for each table.I will use this in MySQL to create all your tables and load sample rows to perform my tests for grading.</li><br>
		</ol>
		<li>A folder named “web-app” containing all source code to make your web application run. The web application needs to properly work with the above MySQL databasedump “movie-sb.sql”. Source code should include proper documentation. A README file is at least required to specify how to run your application.</li>
	</ol>

</div>

app/views/pages/home.html.erb
<h2 class="page-title">MovieBase Status</h2>

<div class="indent">

	<b><u/>4/14/17 UPDATE:</u></b>
	<ul>
		<li>All Table Pages have been standardized</li>
	</ul>

	<b><u/>4/12/17 UPDATE:</u></b>
	<ul>
		<li>All Tables have been Re-Generated, and new links have been added.</li>
		<li>The Schemas page has been updated.</li>
	</ul>

	<b><u>3/22/17 UPDATE:</u></b>
	<ul>
		<li>All Tables have been Generated, and new links have been added.</li>
	</ul>

	<b><u>3/15/17 UPDATE:</u></b>
	<ul>
		<li>A <em><b>Mid-Semester Deliverables Page</b></em> has been added. That page lists all required Mid-Semester Deliverables and will be used to check off our required items. Below the requirements list is our compiled deliverables so far.</li><br>
		<li>A <em><b>Final Deliverables Page</b></em> has been set up with the exact same setup.</li><br>
		<li>Added a Note about Users under the <em><b>Schema Page</b></em></li>
	</ul>

	<br>

	<b><u>3/14/17 UPDATE:</u></b> 
	<ul>
		<li>Database Table Schemas have been added under the <em><b>Schemas Page</b></em> above. </li>
	</ul>

	<br>

	<b><u>INITIAL UPDATE:</u></b>
	<ul>
		<li>This is the main Home page located in app/views/page/home.html.erb</li><br>
		<li>The Page controller has been generated allowing us to make static pages. </li>
	</ul>

</div>

app/views/pages/mid.html.erb
<h2 class="page-title">Mid-Semester Deliverables</h2>

<div class="indent">

	<br/>
	<center>
	<b><u><strong><big>WE GOT A 90 / 100 ON MIDSEMESTER DELIVERABLES</big></strong></u></b>
	</center>

	<br/>
	<br/>

	<b><u>Here are the Mid-Semester Deliverables due on March 20th:</u></b>
	<br/>
	<em><b>NOTE:</b></em> Items with a &#10004; have been completed.
	<br/>
	For each team, please submit a compressed file containing the following: 
	<br/>
	<ol>
		<li>A PDF report named “mid-report.pdf” including:</li>
		<br/>
		<ol>
			<li>&#10004; Team members and each member’s responsibility (up to 4 members per team).</li><br/>
			<li>&#10004;Describe your database design and assumptions (these should meet the minimum requirements specified previously). Develop a corresponding ER diagram for your database, including entities, attributes, relationships, andstructural constraints.</li><br/>
		 <li>&#10004; Design database schema (e.g., MySQL table names, column names, data types). All primary key and foreign keys should be logically chosen. </li><br/>
		</ol>
		<li>&#10004;A MySQL dump file named “movie-db.sql”, containing:</li><br/>
		<ol>
			<li>&#10004;CREATE TABLE statements (DDL) for each table. Use AUTO_INCREMENT integers for primary keys, which could be used as foreign keys in other tables.Foreign key constraints (or referential constraints) should be specified.</li><br/>
			<li>&#10004;INSERT statements (DML) with at least 10 sample rows inserted for each table.</li><br/>
		</ol>
	</ol>
	<br/>
	<b><u>Our Deliverables So Far:</u></b>
	<br/>
	<ol>
		<li>&#10004;We will generate our pdf report from the info below:</li>
		<br/>
		<ol>
			<li>&#10004; Sam Caplan - Testing and Functionality Compliance, Matt Jackson - Database Designer, Mitch Mullins - Web Interface Developer (NOTE: We can come up with better responsibilities names. I just made these up)</li><br/>
			<li>&#10004;Describe your database design and assumptions (these should meet the minimum requirements specified previously). Develop a corresponding ER diagram for your database, including entities, attributes, relationships, andstructural constraints.</li><br/>
		 <li>&#10004; If we are good with the schemas laid out on the schemas page, then we can copy and paste them into what will be our pdf.</li><br/>
		</ol>
		<li>&#10004;A MySQL dump file named “movie-db.sql”, containing:</li><br/>
		<ol>
			<li>&#10004;CREATE TABLE statements (DDL) for each table. Use AUTO_INCREMENT integers for primary keys, which could be used as foreign keys in other tables.Foreign key constraints (or referential constraints) should be specified.</li><br/>
			<li>&#10004;INSERT statements (DML) with at least 10 sample rows inserted for each table.</li><br/>
		</ol>
	</ol>

</div>

app/views/pages/schema.html.erb
<h2 class="page-title">Schemas</h2>

<div class="indent">

In the Main V2_MOVIEBASE Database would be the following tables:

<br>
<br>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="8" >
		Movies
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Movie ID
		</td>
		<td>
			Title
		</td>
		<td>
			Summary
		</td>
		<td>
			Release
		</td>
		<td>
			Language
		</td>
		<td>
			Duration
		</td>
		<td>
			Image
		</td>
		<td>
			Video
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			String
		</td>
		<td>
			Text
		</td>
		<td>
			String
		</td>
		<td>
			String
		</td>
		<td>
			String
		</td>
		<td>
			String
		</td>
		<td>
			String
		</td>
	</tr>
</table>

<br/>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="2">
			Movie Genres
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Movie ID
		</td>
		<td>
			Genre ID
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			Integer
		</td>
	</tr>
</table>

<br/>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="2">
			Genres
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Genre ID
		</td>
		<td>
			Genre
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			String
		</td>
	</tr>
</table>

<br>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="4">
			Reviews
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Movie ID
		</td>
		<td>
			User ID
		</td>
		<td>
			Ratings
		</td>
		<td>
			Reviews
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			Integer
		</td>
		<td>
			Integer (Out of 5 Stars)
		</td>
		<td>
			Text
		</td>
	</tr>
</table>

<br/>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="2">
			Tags
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Tag ID
		</td>
		<td>
			Tag
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			String
		</td>
	</tr>
</table>

<br/>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="2">
			Movie Tags
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Movie ID
		</td>
		<td>
			Tag ID
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			Integer
		</td>
	</tr>
</table>

<br>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="8">
			Movie Crew
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Movie ID
		</td>
		<td>
			Producer
		</td>
		<td>
			Director
		</td>
		<td>
			Sound Effects/Score Composer
		</td>
		<td>
			Lighting
		</td>
		<td>
			Screenwriters
		</td>
		<td>
			Actors
		</td>
		<td>
			Editors
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			Text
		</td>
		<td>
			Text
		</td>
		<td>
			Text
		</td>
		<td>
			Text
		</td>
		<td>
			Text
		</td>
		<td>
			Text
		</td>
		<td>
			Text
		</td>
	</tr>
</table>

<br/>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="2">
			People
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			Person ID
		</td>
		<td>
			Name
		</td>
	</tr>
	<tr>
		<td>
			Integer
		</td>
		<td>
			String
		</td>
	</tr>
</table>

<br>

<table style="border-collapse: collapse; border: 1px solid black; text-align: center;">
	<tr style="background: black; color: white;">
		<td colspan="7">
			Users
		</td>
	</tr>
	<tr style="background: white; color: black;">
		<td>
			First Name
		</td>
		<td>
			Middle Name (optional)
		</td>
		<td>
			Last Name
		</td>
		<td>
			Date of Birth
		</td>
		<td>
			Gender
		</td>
		<td>
			Permissions
		</td>
		<td>
			Watchlist
		</td>
	</tr>
	<tr>
		<td>
			String
		</td>
		<td>
			String
		</td>
		<td>
			String
		</td>
		<td>
			String
		</td>
		<td>
			String
		</td>
		<td>
			Text
		</td>
		<td>
			Text
		</td>
	</tr>
</table>

</div>